# -*- coding: utf-8 -*-
"""392. Is Subsequence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UyDXtxOLfFy0RIzf_FxX1w0Xmrue1O8j
"""

class Solution:
    def isSubsequence(self, s: str, t: str) -> bool:
        s_idx = 0
        for t_idx in range(len(t)):
            if s_idx == len(s):
                return True
            if s[s_idx] == t[t_idx]:
                s_idx += 1
        return s_idx == len(s)