# -*- coding: utf-8 -*-
"""2235. Add Two Integers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dpC_fx5sgrIHaQ2K-Sr3pSe5U2CNGFVQ

#2235. Add Two Integers
"""

class Solution(object):
    def sum(self, num1, num2):
        """
        :type num1: int
        :type num2: int
        :rtype: int
        """
        return num1 + num2

sol=Solution()
result=sol.sum(5,9)
print(result)

