# -*- coding: utf-8 -*-
"""9. Palindrome Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQ-FiiMHAl34cgPbgMx8-3277Uepp0u9
"""

class Solution:
    def isPalindrome(self, x: int) -> bool:
        x=str(x)
        return x==x[::-1]