# -*- coding: utf-8 -*-
"""876. Middle of the Linked List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nw5J7034QM0TlZZfVOZ3ocDIQ6OA0qcu
"""

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def middleNode(self, head: Optional[ListNode]) -> Optional[ListNode]:
        result=[head]
        while result[-1].next != None:
            result.append(result[-1].next)
        return result[len(result)//2]