# -*- coding: utf-8 -*-
"""1480. Running Sum of 1d Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iZM0IwIqwBzDQ_ltASD1FucNPiiAGCZZ
"""

from typing import List
class Solution:
    def runningSum(self, nums: List[int]) -> List[int]:
        result = []
        result.append(nums[0])
        for i in range(1,len(nums)):
            result.append(nums[i]+result[i-1])
        return result

s=Solution()
s.runningSum([1,3,7,3])