# -*- coding: utf-8 -*-
"""389. Find the Difference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wsqKfCUYH-DP2zraXT8NLOWXJxgvdzKw
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s = sorted(s)
        t = sorted(t)
        for i in range(len(s)):
            if t[i] != s[i]:
                return t[i]
        return t[-1]