# -*- coding: utf-8 -*-
"""1672. Richest Customer Wealth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KNNi-AQEddXPQ5iMaoqmEC9salPcdQX1
"""

from typing import List
class Solution:
    def maximumWealth(self, accounts: List[List[int]]) -> int:
        max=0
        for i in accounts:
            sum=0
            for j in i:
                sum+=j
            if(max<sum):
                max=sum
        return max

s=Solution()
s.maximumWealth([[1,5,3],[3,2,1]])