# -*- coding: utf-8 -*-
"""1342. Number of Steps to Reduce a Number to Zero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wP8f2yCd1odbMXvQyuzda2T7Xh-DsQZy
"""

class Solution:
    def numberOfSteps(self, num: int) -> int:
        count=0
        while(num != 0):
            if(num%2 == 0):
                num//=2
            else:
                num-=1
            count+=1
        return count

s=Solution()
s.numberOfSteps(5)

